humanoid_league_interactive_marker:
  ros__parameters:
    # Used to determine if object should be visible
    camera_info:  # Updated to jacks camera info from wide angle camera
      frame_id: "camera_optical_frame"
      height: 1536
      width: 2048
      K: [1338.64532, 0.        , 1026.12387,
          0.        , 1337.89746, 748.42213 ,
          0.        , 0.        , 1.         ]
